config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  #mainly static pages
  match '/home', to: 'main#index', via: [:get, :post]
  match '/about', to: 'main#about', via: [:get, :post]

  #contact pages
  get '/contact', to: 'messages#new', as: 'contact'
  post '/contact', to: 'messages#create'

  #login / logout pages
  get '/admin', to: 'sessions#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #ActiveRecord resource pages
  resources :products, path: 'gallery' do
    resources :item_images
    post 'addToOrder', on: :member
    post 'removeFromOrder', on: :member
  end

  resources :gallery_category

  resources :orders, only: [:show, :create,:destroy,:update] do
    patch 'payment_approved', on: :member
    get 'shipped', on: :member
    get 'completed', on: :member
  end
  get '/cart', to: 'orders#cart'
  get '/admin/orders', to: 'orders#manage'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :require_login

  def index
  end

  def about
  end

  def temp_cart
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/about.html.erb
<div class='row'>
  <div class='col-lg-8'>
    <div class='panel panel-info'>
      <div class='panel-heading'>
        <h2 class='panel-title'>About the Artist</h2>
      </div>
      <div class='panel-body'>
        <p>For over twenty-five years I have casually worked with stained glass creating sun catchers, panels, kaleidoscopes and other basic items but I could not find satisfaction in my work.   During that time I worked at a professional career in banking and while I did well professionally I began to feel that the artist in me needed to find something more satisfying.  One day while visiting the store where I purchase my glass supplies I noticed the addition to the warehouse of a large kiln and a conversation quickly began about glass fussing and I immediately knew it was something that I had to do and from that point on, I  looked at glass in a totally different way.  It was not too long before I began fusing glass in a small kiln making jewelry and other small pieces.  My love of glass was quickly growing and I realized that there are endless possibilities of what could be created from glass and before I knew it I was purchasing a larger kiln!</p>

        <p>Soon after the purchase of my kiln and after twenty-eight years of employment with the same bank I found my professional career over due to mergers and downsizing and while it has been stressful and sad I look to the positive and allow my passion for glass to grow and begin the next chapters of my life. My glass projects have been growing from the small pieces of jewelry that I first created to larger dishes, candle holders, cheese trays and more. As the size of my projects grow so has my passion for glass and the endless possibilities of what can be created!</p>

        <p>Each creation from glass is handmade and unique and no two pieces will ever look exactly alike, however if you have a specific piece or color in mind for a bowl, plate, or piece of jewelry please let me know and I will do my best to create your vision.</p>
      </div>
    </div>
  </div>

  <%= render 'sidebar' %>

</div>

app/views/main/index.html.erb
<div class='row'>
  <div class='col-lg-8'>
    <div class='panel panel-info'>
      <div class='panel-heading'>
        <h3 class='panel-title'>Welcome!</h3>
      </div>
      <div class='panel-body'>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>
          <div class="carousel-inner" role="listbox" >
            <div class="item active" style="height:500px">
              <%= image_tag image_url('carousel/1.jpg'), style: 'min-height:100%;min-width:100%;margin:auto' %>
            </div>
            <div class="item" style="height:500px">
              <%= image_tag image_url('carousel/2.jpg'), style: 'min-height:100%;min-width:100%;margin:auto' %>
            </div>
            <div class="item" style="height:500px">
              <%= image_tag image_url('carousel/3.jpg'), style: 'min-height:100%;min-width:100%;margin:auto' %>
            </div>
            <div class="item" style="height:500px">
              <%= image_tag image_url('carousel/4.jpg'), style: 'min-height:100%;min-width:100%;margin:auto' %>
            </div>
          </div>
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div><br/>

        <p>Jenni Zimmerman is an artist who has worked with glass for over 25 years, starting with stained glass, she has focused on glass fusing for about 15 years.  Starting small with cabochons for jewelry to larger dishes for display and servings she also uses a variety of recycled glass for a variety of unusual items. </p>
        <%= link_to 'Read More About Us', '/about', class: 'btn btn-primary' %>
        <%= link_to 'View Gallery', products_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  <%= render "sidebar" %>
</div>