config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  #mainly static pages
  match '/home', to: 'main#index', via: [:get, :post]
  match '/about', to: 'main#about', via: [:get, :post]

  #contact pages
  get '/contact', to: 'messages#new', as: 'contact'
  post '/contact', to: 'messages#create'

  #login / logout pages
  get '/admin', to: 'sessions#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #ActiveRecord resource pages
  resources :products, path: 'gallery' do
    resources :item_images
    post 'addToOrder', on: :member
    post 'removeFromOrder', on: :member
  end

  resources :gallery_category

  resources :orders, only: [:show, :create,:destroy,:update] do
    patch 'payment_approved', on: :member
    get 'shipped', on: :member
    get 'completed', on: :member
  end
  get '/cart', to: 'orders#cart'
  get '/admin/orders', to: 'orders#manage'

end

app/models/gallery_category.rb
class GalleryCategory < ApplicationRecord
end

app/controllers/gallery_category_controller.rb
class GalleryCategoryController < ApplicationController

  def new
    @category = GalleryCategory.new
  end

  def create
    @category = GalleryCategory.new(category_params)

    if @category.save!
      update_category_names
    end

    redirect_to gallery_category_index_path
  end

  def edit
    @category = GalleryCategory.find(params[:id])
  end

  def update
    @category = GalleryCategory.find(params[:id])

    if @category.update_attributes(category_params)
      update_category_names
      redirect_to gallery_category_index_path
    else
      redirect_to edit_gallery_category_path(@category)
    end
  end

  def index
    @categories = GalleryCategory.all
  end

  def destroy
    @category = GalleryCategory.find(params[:id])

    if @category.destroy!

      @products = Product.where(gallery_category: @category.id)
      @products.each do |p|
        p.update_attributes({"gallery_category" => nil})
      end

      update_category_names

      redirect_to gallery_category_index_path
      
    else
      redirect_to edit_gallery_category_path(@category)
    end
  end

  private
    def category_params
      params.require(:gallery_category).permit(:name, :description)
    end

end

app/helpers/gallery_category_helper.rb
module GalleryCategoryHelper
end

app/views/gallery_category/_form.html.erb
<%= form_for @category, url: url_for(controller: 'gallery_category', action: @action),html: {multipart: true} do |f| %>

  <div class='form-group row'>
    <%= f.label :name, class: 'col-sm-1 col-form-label' %>
    <div class='col-sm-3'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group row'>
    <%= f.label :description, class: 'col-sm-1 col-form-label' %>
    <div class='col-sm-3'>
      <%= f.text_area :description, class: 'form-control', rows: 4 %>
    </div>
  </div>

  <%= f.submit 'Save', class: 'btn btn-success' %>

<% end %>

app/views/gallery_category/edit.html.erb
<div class='panel panel-info'>
  <div class='panel-heading'>
    <h3 class='panel-title'>New Gallery Category</h3>
  </div>
  <div class='panel-body'>
    <% @action = 'update' %>
    <%= render "form" %>
  </div>
</div>

app/views/gallery_category/index.html.erb
<div class='panel panel-info'>
  <div class='panel-heading'>
    <h3 class='panel-title'>Gallery Categories</h3>
  </div>
  <div class='panel-body'>
    <div class='row'>
      <div class='col-md-6'
        <% if @categories.present? %>
          <ul class='list-group'>
            <% @categories.each do |c| %>
              <li class='list-group-item clearfix'>
                <%= c.name %>
                <span class='pull-right'>
                  <%= link_to 'Edit', edit_gallery_category_path(c), class: 'btn btn-primary'%>
                  <%= link_to 'Delete', gallery_category_path(c), method: 'delete', class: 'btn btn-danger'%>
                </span>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/gallery_category/new.html.erb
<div class='panel panel-info'>
  <div class='panel-heading'>
    <h3 class='panel-title'>New Gallery Category</h3>
  </div>
  <div class='panel-body'>
    <% @action = 'create' %>
    <%= render "form" %>
  </div>
</div>