config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  #mainly static pages
  match '/home', to: 'main#index', via: [:get, :post]
  match '/about', to: 'main#about', via: [:get, :post]

  #contact pages
  get '/contact', to: 'messages#new', as: 'contact'
  post '/contact', to: 'messages#create'

  #login / logout pages
  get '/admin', to: 'sessions#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #ActiveRecord resource pages
  resources :products, path: 'gallery' do
    resources :item_images
    post 'addToOrder', on: :member
    post 'removeFromOrder', on: :member
  end

  resources :gallery_category

  resources :orders, only: [:show, :create,:destroy,:update] do
    patch 'payment_approved', on: :member
    get 'shipped', on: :member
    get 'completed', on: :member
  end
  get '/cart', to: 'orders#cart'
  get '/admin/orders', to: 'orders#manage'

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :products

  def placed?
    return status == 'ordered' || status == 'shipped' || status =='completed'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :require_login, except: [:manage, :shipped, :completed]

  require  'paypal-sdk-rest'
  include PayPal::SDK::REST

  def create
  end

  def update

    @order = ::Order.find(params[:id])

    #pull out the parameters here to be used

    @order.billing_first_name = params[:order][:billing_first_name]
    @order.billing_last_name = params[:order][:billing_last_name]
    @order.email = params[:order][:email]
    @order.billing_address1 = params[:order][:billing_address1]
    @order.billing_address2 = params[:order][:billing_address2]
    @order.billing_city = params[:order][:billing_city]
    @order.billing_state = params[:order][:billing_state]
    @order.billing_zip = params[:order][:billing_zip]

    @order.shipping_name = params[:order][:shipping_name]
    @order.shipping_address1 = params[:order][:shipping_address1]
    @order.shipping_address2 = params[:order][:shipping_address2]
    @order.shipping_city = params[:order][:shipping_city]
    @order.shipping_state = params[:order][:shipping_state]
    @order.shipping_zip = params[:order][:shipping_zip]

    @order.card_type = params[:order][:card_type]
    @order.card_number = params[:order][:card_number]
    @order.card_exp_month = params[:order][:card_exp_month]
    @order.card_exp_year = params[:order][:card_exp_year]
    @order.card_cvv2 = params[:order][:card_cvv2]

    @order.tax = @order.subtotal * 0.07
    @order.shipping = 10.00

    @order.total = @order.subtotal + @order.tax + @order.shipping

    if @order.save!
      session[:order_accepted] = true

    else
      flash[:error] = 'There was an error saving your billing info'
    end
    redirect_to url_for(controller: 'orders', action: 'show')

  end


  def cart

    if !session[:order_id].nil?

      render_order(session[:order_id])
    end
  end

  def show
    render_order(params[:id])
  end

  def manage
    @panels = []
    @panels.push({
      id: 'placedOrders',
      title: 'Recently Placed Orders',
      orders: ::Order.where(status: 'ordered')
      })
    @panels.push({
      id: 'shippedOrders',
      title: 'Recently Shipped Orders',
      orders: ::Order.where(status: 'shipped')
      })
    @panels.push({
      id: 'completedOrders',
      title: 'Completed Orders',
      orders: ::Order.where(status: 'completed')
      })
  end

  def payment_approved
    logger.info params
    @order = ::Order.find(params[:id])

    payment = params[:payment]

    #save paypal resource ids
    @order.payment_id = payment[:id]
    @order.sale_id = payment[:transactions][0][:related_resources][0][:sale][:id]

    #save ordering persons info
    payer = payment[:payer][:payer_info]
    @order.email = payer[:email]
    @order.name = payer[:first_name]+' '+payer[:last_name]
    @order.shipping_name = payer[:shipping_address][:recipient_name]
    @order.shipping_address1 = payer[:shipping_address][:line1]
    @order.shipping_address2 = payer[:shipping_address][:line2]
    @order.shipping_city = payer[:shipping_address][:city]
    @order.shipping_state = payer[:shipping_address][:state]
    @order.shipping_zip = payer[:shipping_address][:postal_code]

    @order.transaction_fee = payment[:transactions][0][:related_resources][0][:sale][:transaction_fee][:value]

    #update order status
    @order.order_date = Date.today
    @order.status = 'ordered'

    @order.save!

    #need to send email to auntjen that an order was placed
    MessageMailer.new_order(@order).deliver

    redirect_to order_path(@order)
  end

  def shipped
    @order = ::Order.find(params[:id])

    if @order.update_attributes!({status: 'shipped'})
      #TODO send some kind of email to the user
      redirect_to admin_orders_path
    else
      #do some error thing
    end
  end

  def completed
    @order = ::Order.find(params[:id])

    if @order.update_attributes({status: 'completed'})
      #archive the items in the order here
      Product.where(order_id: @order.id).each do |i|
        i.update_attributes!({archived: true})
      end
      redirect_to admin_orders_path
    else
      #do some error thing
    end
  end

  def destroy
  end


  private
  def create_item_array(order_id)
    orderItems = Product.where(order_id: order_id)

    item_array = []

    for item in orderItems
      item_array.push({name: item.name,
      sku: item.id,
      price: item.price,
      currency: 'USD',
      quantity: 1})
    end

    return item_array
  end

  def render_order(order_id)

    if ::Order.exists?(id: order_id)

      @order = ::Order.find(order_id)

      @orderItems = Product.where(order_id: @order.id)

      if @order.placed?
        @cartTitle = 'Thanks for your order!'
        @orderCompleted = true
      else
        #else the order hasn't been placed yet
        @cartTitle = 'Your Cart'
        @orderCompleted = false

        #update order costs here
        @order.tax = @order.subtotal * 0.07
        @order.shipping = 10
        @order.total = @order.subtotal + @order.tax + @order.shipping
        @order.save!

        @transactions = {
          transactions: [{
            item_list: {
              items: create_item_array(@order.id)
            },
            amount: {
              total: '%.2f' % @order.total,
              currency: 'USD',
              details: {
                subtotal: '%.2f' % @order.subtotal,
                tax: '%.2f' % @order.tax,
                shipping: '%.2f' % @order.shipping
              }
            },
            description: 'Order from Studio Balu Designs'
        }]}.to_json.html_safe
      end

    else
      if !session[:order_id].nil?
        session[:order_id] = nil
      end
      @cartTitle = 'Cart Empty'
    end

    render "show"
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/manage.html.erb
<% @panels.each do |p| %>
  <div class='panel-group'>
    <div class='panel panel-info'>
      <div class='panel-heading'>
        <h3 class='panel-title'><%= p[:title] %></h3>
      </div>

      <div class='panel-body' id='<%= p[:id] %>'>
        <% if p[:orders].length == 0 %>
          <p>There are no <%= p[:title] %></p>
        <% else %>
          <div class='panel-group'>
            <% p[:orders].each do |i| %>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <div class='panel-title'>
                    <a data-toggle='collapse' data-parent='#<%= p[:id] %>' href='#Order-<%= i.id %>'>
                      Order #<%= i.id %>
                    </a>
                    <span class='pull-right'>Total: <%= i.total %></span>
                  </div>
                </div>
                <div id='Order-<%= i.id %>' class='panel-collpase collapse'>
                  <div class='panel-body'>
                    <div class='row'>
                      <div class='col-md-4'>
                        <!-- Ordered Details -->
                        <h4>Order Details</h4>
                        <p>Ordered by: <%= i.name %></p>
                        <p><a href='mailto:<%= i.email %>'><%= i.email %></a></p>
                        <p>Ordered on: <%= i.order_date %></p>

                      </div>

                      <div class='col-sm-4'>
                        <!-- Shipping Info-->
                        <h4>Shipping Info</h4>
                        <p><%= i.shipping_name%></p>
                        <p><%= i.shipping_address1%></p>
                        <% if !i.shipping_address2.nil? %>
                          <p><%= i.shipping_address2%></p>
                        <% end %>
                        <p><%= i.shipping_city.to_s + ', ' + i.shipping_state.to_s + ' ' + i.shipping_zip.to_s %></p>
                      </div>

                      <div class='col-sm-4'>
                        <!-- Item List -->
                        <div class='list-group'>
                          <% Product.where(order_id: i.id).each do |j| %>
                            <div class='list-group-item'>
                              <div class='row'>
                                <div class='col-sm-8'>
                                  <%= j.name %>
                                </div>
                                <div class='col-sm-4'>
                                  $<%= '%.2f' % j.price %>
                                </div>
                              </div>
                            </div>
                          <% end %>
                          <div class='list-group-item'>
                            <div class='row'>
                              <div class='col-sm-8 pull-right'>
                                <span class='col-sm-6'>Subtotal: </span>
                                <span class='col-sm-6'>$<%='%.2f' % i.subtotal %></span>
                              </div>
                            </div>
                            <div class='row'>
                              <div class='col-sm-8 pull-right'>
                                <span class='col-sm-6'>Tax: </span>
                                <span class='col-sm-6'>$<%='%.2f' % i.tax %></span>
                              </div>
                            </div>
                            <div class='row'>
                              <div class='col-sm-8 pull-right'>
                                <span class='col-sm-6'>Shipping: </span>
                                <span class='col-sm-6'>$<%='%.2f' % i.shipping %></span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class='row'>
                      <!-- button row -->
                      <div class='col-sm-12'>
                        <% if p[:id] == 'placedOrders' %>
                          <a class='btn btn-primary' href='<%= shipped_order_path(i.id) %>' role='button'>Ship Order</a>
                        <% elsif p[:id] == 'shippedOrders' %>
                          <a class='btn btn-primary' href='<%= completed_order_path(i.id) %>' role='button'>Complete Order</a>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/orders/show.html.erb
<div class='panel panel-info'>

  <div class='panel-heading'>
    <h3 class='panel-title'><%= @cartTitle %></h3>
  </div>

  <div class='panel-body'>

    <% if @orderCompleted %>
      <h1>Order Number: <%= @order.id %></h1>
      <h3>Status: <%= @order.status.capitalize %></h3>
    <%end%>

    <% if !@order.nil? && @orderItems.length > 0%>
      <div class='row'>
        <div class='col-lg-12'>
          <div class='list-group'>

            <% @orderItems.each do |i| %>
              <div class='list-group-item'>
                <div class='row'>
                  <div class='col-sm-8'>
                    <%= i.name %>
                  </div>
                  <div class='col-sm-4'>
                    $<%= '%.2f' % i.price %>
                    <% if !@orderCompleted %>
                      <%= link_to 'X', removeFromOrder_product_path(i), class: 'btn btn-danger pull-right', method: :post %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div class='list-group-item'>
              <div class='row'>
                <div class='col-sm-4 pull-right'>
                  <span class='col-sm-6'>Subtotal: </span>
                  <span class='col-sm-6'>$<%='%.2f' % @order.subtotal %></span>
                </div>
              </div>
              <div class='row'>
                <div class='col-sm-4 pull-right'>
                  <span class='col-sm-6'>Tax: </span>
                  <span class='col-sm-6'>$<%='%.2f' % @order.tax %></span>
                </div>
              </div>
              <div class='row'>
                <div class='col-sm-4 pull-right'>
                  <span class='col-sm-6'>Shipping: </span>
                  <span class='col-sm-6'>$<%='%.2f' % @order.shipping %></span>
                </div>
              </div>
              <div class='row'>
                <div class='col-sm-4 pull-right'>
                  <strong>
                    <span class='col-sm-6'>Total: </span>
                    <span class='col-sm-6'>$<%='%.2f' % @order.total %></span>
                  </strong>
                </div>
              </div>
            </div>


            <br>

            <% if !@orderCompleted %>
              <!-- Create paypal button -->
              <div class='row'>
                <div class='pull-right'>
                  <div id='btnPayNow' style='display:inline-block' class='btn'></div>
                  <input id='transactions' type='hidden' value ='<%= @transactions %>'/>
                  <input id='redirectURL' type='hidden' value='<%=payment_approved_order_url(@order) %>'/>
                  <script>
                  var attached;
                  if (!attached) {
                    $(document).on('turbolinks:load', function() {
                      if ($('#btnPayNow').length) {
                        paypal.Button.render({
                          env: "<%= ENV['PAYPAL_ENV']  %>",
                          style: {
                            label: 'checkout',
                            size: 'responsive',
                            shape: 'rect',
                            color: 'blue'
                          },
                          commit: true,
                          client: {
                            sandbox: "<%= ENV['PAYPAL_SANDBOX_KEY'] %>",
                            production: "<%= ENV['PAYPAL_PRODUCTION_KEY'] %>"
                          },
                          payment: function (actions) {
                            var transactions = '<%= @transactions %>';
                            //console.log(transactions);
                            return result = actions.payment.create(JSON.parse(transactions));
                          },
                          onAuthorize: function(data,actions) {
                            return actions.payment.execute().then(function(payment){
                              //payment complete
                              //console.log(payment);
                              var paymentStr = JSON.stringify({'payment':payment});
                              $.ajax({
                                url: $("#redirectURL").val(),
                                data: paymentStr,
                                type: 'PATCH',
                                contentType: 'application/json',
                                cache: false
                              });
                            });
                          }
                        }, '#btnPayNow');
                      }
                    });
                    attached = true;
                  }
                  </script>
                </div>
              </div><!-- paypal button -->
            <% end %>

          </div>
        </div>
      </div>

      <%if @orderCompleted %>
        <div class='row'>
          <div class='col-md-6'>
            <h4>Shipping Information</h4>
            <p><%=@order.shipping_name%></p>
            <p><%=@order.shipping_address1%></p>
            <% if !@order.shipping_address2.nil? %>
              <p><%=@order.shipping_address2%></p>
            <% end %>
            <p><%=@order.shipping_city.to_s + ', ' + @order.shipping_state.to_s + ' ' + @order.shipping_zip.to_s %></p>
          </div>
        </div>
      <% end %>
    <% else %>
      <h4>Add items to your cart and come back!</h4>
    <% end %>
  </div>
</div>